In [2]:
import numpy as np 
import pandas as pd

In [4]:


customer_df = pd.read_csv(
    r"D:\Customer_Churn_Retention_Analysis\01_Raw_Data\customer_data.csv"
)

transaction_df = pd.read_csv(
    r"D:\Customer_Churn_Retention_Analysis\01_Raw_Data\transactions_data.csv"
)

In [5]:
customer_df.head()

,customer_id,age,gender,location,income_bracket,occupation,education_level,marital_status,household_size,acquisition_channel,...,total_transaction_volume,transaction_frequency,last_transaction_date,preferred_transaction_type,first_transaction_date,weekend_transaction_ratio,avg_daily_transactions,customer_tenure,churn_probability,customer_lifetime_value
0,93716481,44,Male,"Pereira, Risaralda",Very High,Engineer,Master,Married,5,Partnership,...,60540250,0.030769,2023-12-05,Transfer,2023-01-05,0.300000,0.030769,11.633333,0.362269,3.124148e+08
1,49020929,44,Male,"Cali, Valle del Cauca",Medium,Construction Worker,Bachelor,Married,2,Paid Ad,...,23401550,0.032934,2023-12-18,Transfer,2023-02-05,0.181818,0.032934,11.500000,0.181790,1.670223e+08
2,52690950,45,Male,"Barranquilla, Atlántico",High,Construction Worker,Bachelor,Married,4,Paid Ad,...,35759150,0.050000,2023-10-27,Transfer,2023-01-31,0.300000,0.050000,8.766667,0.321265,1.940371e+07
3,23199751,45,Male,"Bogotá, Cundinamarca",High,Electrician,High School,Single,2,Referral,...,21186950,0.047782,2023-11-30,Transfer,2023-01-10,0.142857,0.047782,10.733333,0.336629,3.597811e+07
4,61997066,44,Female,"Bogotá, Cundinamarca",Medium,Cleaner,Bachelor,Married,3,Paid Ad,...,11640800,0.061889,2023-11-17,Payment,2023-01-05,0.315789,0.061889,11.633333,0.398151,3.046620e+08

In [6]:
transaction_df.head()

   customer_id        date   amount        type
0     93716481  2023-11-23  1262800    Transfer
1     93716481  2023-01-05   928900  Withdrawal
2     93716481  2023-11-05  1683100     Payment
3     93716481  2023-04-14  4507350     Payment
4     93716481  2023-08-04  2096150     Payment

In [7]:
customer_df.shape

(48723, 54)

In [8]:
customer_df.columns.to_list()

['customer_id',
 'age',
 'gender',
 'location',
 'income_bracket',
 'occupation',
 'education_level',
 'marital_status',
 'household_size',
 'acquisition_channel',
 'customer_segment',
 'savings_account',
 'credit_card',
 'personal_loan',
 'investment_account',
 'insurance_product',
 'active_products',
 'app_logins_frequency',
 'feature_usage_diversity',
 'bill_payment_user',
 'auto_savings_enabled',
 'credit_utilization_ratio',
 'international_transactions',
 'failed_transactions',
 'tx_count',
 'avg_tx_value',
 'total_tx_volume',
 'first_tx',
 'last_tx',
 'base_satisfaction',
 'tx_satisfaction',
 'product_satisfaction',
 'satisfaction_score',
 'nps_score',
 'last_survey_date',
 'support_tickets_count',
 'resolved_tickets_ratio',
 'app_store_rating',
 'feedback_sentiment',
 'feature_requests',
 'complaint_topics',
 'clv_segment',
 'monthly_transaction_count',
 'average_transaction_value',
 'total_transaction_volume',
 'transaction_frequency',
 'last_transaction_date',
 'preferred_transaction_type',
 'first_transaction_date',
 'weekend_transaction_ratio',
 'avg_daily_transactions',
 'customer_tenure',
 'churn_probability',
 'customer_lifetime_value']

In [9]:
customer_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48723 entries, 0 to 48722
Data columns (total 54 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customer_id                 48723 non-null  int64
 1   age                         48723 non-null  int64
 2   gender                      48723 non-null  str
 3   location                    48723 non-null  str
 4   income_bracket              48723 non-null  str
 5   occupation                  48723 non-null  str
 6   education_level             48723 non-null  str
 7   marital_status              48723 non-null  str
 8   household_size              48723 non-null  int64
 9   acquisition_channel         48723 non-null  str
 10  customer_segment            48723 non-null  str
 11  savings_account             48723 non-null  bool
 12  credit_card                 48723 non-null  bool
 13  personal_loan               48723 non-null  bool
 14  investment_account          48723 non-null  bool
 15  insurance_product           48723 non-null  bool
 16  active_products             48723 non-null  int64
 17  app_logins_frequency        48723 non-null  int64
 18  feature_usage_diversity     48723 non-null  int64
 19  bill_payment_user           48723 non-null  bool
 20  auto_savings_enabled        48723 non-null  bool
 21  credit_utilization_ratio    30460 non-null  float64
 22  international_transactions  48723 non-null  int64
 23  failed_transactions         48723 non-null  int64
 24  tx_count                    48723 non-null  int64
 25  avg_tx_value                48723 non-null  float64
 26  total_tx_volume             48723 non-null  int64
 27  first_tx                    48723 non-null  str
 28  last_tx                     48723 non-null  str
 29  base_satisfaction           48723 non-null  float64
 30  tx_satisfaction             48723 non-null  float64
 31  product_satisfaction        48723 non-null  float64
 32  satisfaction_score          48723 non-null  int64
 33  nps_score                   48723 non-null  int64
 34  last_survey_date            48723 non-null  str
 35  support_tickets_count       48723 non-null  int64
 36  resolved_tickets_ratio      48723 non-null  float64
 37  app_store_rating            48723 non-null  float64
 38  feedback_sentiment          48723 non-null  str
 39  feature_requests            32608 non-null  str
 40  complaint_topics            24377 non-null  str
 41  clv_segment                 48723 non-null  str
 42  monthly_transaction_count   48723 non-null  float64
 43  average_transaction_value   48723 non-null  float64
 44  total_transaction_volume    48723 non-null  int64
 45  transaction_frequency       48723 non-null  float64
 46  last_transaction_date       48723 non-null  str
 47  preferred_transaction_type  48723 non-null  str
 48  first_transaction_date      48723 non-null  str
 49  weekend_transaction_ratio   48723 non-null  float64
 50  avg_daily_transactions      48723 non-null  float64
 51  customer_tenure             48723 non-null  float64
 52  churn_probability           48723 non-null  float64
 53  customer_lifetime_value     48723 non-null  float64
dtypes: bool(7), float64(15), int64(14), str(18)
memory usage: 17.8 MB

In [14]:
missing = customer_df.isnull().sum()

missing[missing > 0].sort_values(ascending=False)

complaint_topics            24346
credit_utilization_ratio    18263
feature_requests            16115
dtype: int64

In [15]:
missing_analysis = pd.DataFrame({
    "Missing_Count": customer_df.isnull().sum(),
    "Missing_Percentage": (customer_df.isnull().mean() * 100).round(2)
})

missing_analysis = missing_analysis[
    missing_analysis["Missing_Count"] > 0
].sort_values("Missing_Percentage", ascending=False)

missing_analysis

                          Missing_Count  Missing_Percentage
complaint_topics                  24346               49.97
credit_utilization_ratio          18263               37.48
feature_requests                  16115               33.07

In [16]:
customer_df.duplicated().sum()

np.int64(0)

In [19]:
pd.DataFrame({
    "Column": customer_df.columns,
    "Data_Type": customer_df.dtypes.astype(str)
})

                                                Column Data_Type
customer_id                                customer_id     int64
age                                                age     int64
gender                                          gender       str
location                                      location       str
income_bracket                          income_bracket       str
occupation                                  occupation       str
education_level                        education_level       str
marital_status                          marital_status       str
household_size                          household_size     int64
acquisition_channel                acquisition_channel       str
customer_segment                      customer_segment       str
savings_account                        savings_account      bool
credit_card                                credit_card      bool
personal_loan                            personal_loan      bool
investment_account                  investment_account      bool
insurance_product                    insurance_product      bool
active_products                        active_products     int64
app_logins_frequency              app_logins_frequency     int64
feature_usage_diversity        feature_usage_diversity     int64
bill_payment_user                    bill_payment_user      bool
auto_savings_enabled              auto_savings_enabled      bool
credit_utilization_ratio      credit_utilization_ratio   float64
international_transactions  international_transactions     int64
failed_transactions                failed_transactions     int64
tx_count                                      tx_count     int64
avg_tx_value                              avg_tx_value   float64
total_tx_volume                        total_tx_volume     int64
first_tx                                      first_tx       str
last_tx                                        last_tx       str
base_satisfaction                    base_satisfaction   float64
tx_satisfaction                        tx_satisfaction   float64
product_satisfaction              product_satisfaction   float64
satisfaction_score                  satisfaction_score     int64
nps_score                                    nps_score     int64
last_survey_date                      last_survey_date       str
support_tickets_count            support_tickets_count     int64
resolved_tickets_ratio          resolved_tickets_ratio   float64
app_store_rating                      app_store_rating   float64
feedback_sentiment                  feedback_sentiment       str
feature_requests                      feature_requests       str
complaint_topics                      complaint_topics       str
clv_segment                                clv_segment       str
monthly_transaction_count    monthly_transaction_count   float64
average_transaction_value    average_transaction_value   float64
total_transaction_volume      total_transaction_volume     int64
transaction_frequency            transaction_frequency   float64
last_transaction_date            last_transaction_date       str
preferred_transaction_type  preferred_transaction_type       str
first_transaction_date          first_transaction_date       str
weekend_transaction_ratio    weekend_transaction_ratio   float64
avg_daily_transactions          avg_daily_transactions   float64
customer_tenure                        customer_tenure   float64
churn_probability                    churn_probability   float64
customer_lifetime_value        customer_lifetime_value   float64

In [20]:
customer_df.dtypes.value_counts()

str        18
float64    15
int64      14
bool        7
Name: count, dtype: int64

In [21]:
customer_df.nunique().sort_values()

credit_card                       2
personal_loan                     2
investment_account                2
insurance_product                 2
savings_account                   2
bill_payment_user                 2
auto_savings_enabled              2
gender                            3
feedback_sentiment                3
income_bracket                    4
customer_segment                  4
acquisition_channel               4
education_level                   4
preferred_transaction_type        4
clv_segment                       4
marital_status                    4
satisfaction_score                5
failed_transactions               5
active_products                   5
complaint_topics                  5
product_satisfaction              6
age                               6
app_store_rating                  7
international_transactions        7
support_tickets_count             8
feature_usage_diversity          11
household_size                   13
resolved_tickets_ratio           16
location                         18
feature_requests                 25
app_logins_frequency             27
occupation                       35
nps_score                        99
last_tx                         174
last_transaction_date           174
first_transaction_date          180
customer_tenure                 180
first_tx                        180
tx_satisfaction                 191
last_survey_date                365
tx_count                        988
monthly_transaction_count      1133
churn_probability              1977
weekend_transaction_ratio      2864
transaction_frequency          6365
avg_daily_transactions         6365
credit_utilization_ratio      30460
total_tx_volume               48277
total_transaction_volume      48277
average_transaction_value     48577
avg_tx_value                  48577
customer_id                   48723
base_satisfaction             48723
customer_lifetime_value       48723
dtype: int64

In [22]:
customer_df.select_dtypes(include=["object", "string"]).columns

Index(['gender', 'location', 'income_bracket', 'occupation', 'education_level',
       'marital_status', 'acquisition_channel', 'customer_segment', 'first_tx',
       'last_tx', 'last_survey_date', 'feedback_sentiment', 'feature_requests',
       'complaint_topics', 'clv_segment', 'last_transaction_date',
       'preferred_transaction_type', 'first_transaction_date'],
      dtype='str')

In [23]:
categorical_columns = [
    "gender",
    "location",
    "income_bracket",
    "occupation",
    "education_level",
    "marital_status",
    "acquisition_channel",
    "customer_segment",
    "feedback_sentiment",
    "feature_requests",
    "complaint_topics",
    "clv_segment",
    "preferred_transaction_type"
]

for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(customer_df[col].value_counts(dropna=False))

--- gender ---
gender
Female    24033
Male      23761
Other       929
Name: count, dtype: int64

--- location ---
location
Bogotá, Cundinamarca          16967
Medellín, Antioquia            7441
Cali, Valle del Cauca          5837
Barranquilla, Atlántico        3826
Cartagena, Bolívar             2416
Cúcuta, Norte de Santander     1969
Bucaramanga, Santander         1889
Santa Marta, Magdalena         1512
Pereira, Risaralda             1421
Ibagué, Tolima                 1046
Manizales, Caldas               973
Pasto, Nariño                   962
Valledupar, Cesar               519
Armenia, Quindío                510
Villavicencio, Meta             499
Neiva, Huila                    496
Sincelejo, Sucre                228
Montería, Córdoba               212
Name: count, dtype: int64

--- income_bracket ---
income_bracket
Medium       19489
Low          14617
High         12180
Very High     2437
Name: count, dtype: int64

--- occupation ---
occupation
Hairdresser            1456
Dentist                1445
Designer               1433
Police Officer         1433
Mechanic               1431
Real Estate Agent      1427
Engineer               1421
Firefighter            1421
Chef                   1421
Waiter                 1413
Veterinarian           1406
Driver                 1405
Farmer                 1402
Bank Teller            1400
Plumber                1399
Lawyer                 1391
Nurse                  1385
Architect              1382
Cashier                1382
Psychologist           1381
Accountant             1379
Construction Worker    1378
Journalist             1378
Doctor                 1378
Programmer             1377
Teacher                1376
Pharmacist             1374
Security Guard         1374
Electrician            1370
Manager                1367
Insurance Agent        1355
Cleaner                1354
Artist                 1354
Salesperson            1346
Musician               1329
Name: count, dtype: int64

--- education_level ---
education_level
Bachelor       19685
High School    19263
Master          7359
PhD             2416
Name: count, dtype: int64

--- marital_status ---
marital_status
Single      21769
Married     19615
Divorced     4954
Widowed      2385
Name: count, dtype: int64

--- acquisition_channel ---
acquisition_channel
Organic        19500
Referral       14546
Paid Ad         9764
Partnership     4913
Name: count, dtype: int64

--- customer_segment ---
customer_segment
occasional    19391
regular       14568
inactive       9904
power          4860
Name: count, dtype: int64

--- feedback_sentiment ---
feedback_sentiment
Positive    38897
Neutral      8346
Negative     1480
Name: count, dtype: int64

--- feature_requests ---
feature_requests
NaN                                                16115
Cryptocurrency trading                              3336
Budgeting tools                                     3301
Savings goals                                       3288
Mobile check deposit                                3244
International transfers                             3227
International transfers, Mobile check deposit        856
Savings goals, Mobile check deposit                  845
Budgeting tools, Mobile check deposit                842
Budgeting tools, Cryptocurrency trading              842
International transfers, Budgeting tools             841
Savings goals, International transfers               830
Mobile check deposit, Budgeting tools                828
Mobile check deposit, Savings goals                  823
Savings goals, Cryptocurrency trading                821
Savings goals, Budgeting tools                       820
Cryptocurrency trading, International transfers      815
Budgeting tools, Savings goals                       804
Mobile check deposit, International transfers        802
Budgeting tools, International transfers             797
International transfers, Cryptocurrency trading      780
International transfers, Savings goals               780
Cryptocurrency trading, Mobile check deposit         778
Mobile check deposit, Cryptocurrency trading         774
Cryptocurrency trading, Budgeting tools              768
Cryptocurrency trading, Savings goals                766
Name: count, dtype: int64

--- complaint_topics ---
complaint_topics
NaN                   24346
Customer service       4940
Fees                   4911
Transaction issues     4867
Account security       4841
App performance        4818
Name: count, dtype: int64

--- clv_segment ---
clv_segment
Bronze      12181
Platinum    12181
Silver      12181
Gold        12180
Name: count, dtype: int64

--- preferred_transaction_type ---
preferred_transaction_type
Transfer      36954
Payment       10002
Withdrawal     1326
Deposit         441
Name: count, dtype: int64

In [24]:
date_columns = [
    "first_tx",
    "last_tx",
    "last_survey_date",
    "last_transaction_date",
    "first_transaction_date"
]

for col in date_columns:
    print(f"\n--- {col} ---")
    print("Data type:", customer_df[col].dtype)
    print("Missing:", customer_df[col].isna().sum())
    print("Sample values:")
    print(customer_df[col].dropna().head())

--- first_tx ---
Data type: str
Missing: 0
Sample values:
0    2023-01-05
1    2023-02-05
2    2023-01-31
3    2023-01-10
4    2023-01-05
Name: first_tx, dtype: str

--- last_tx ---
Data type: str
Missing: 0
Sample values:
0    2023-12-25
1    2023-12-20
2    2023-12-12
3    2023-12-24
4    2023-11-27
Name: last_tx, dtype: str

--- last_survey_date ---
Data type: str
Missing: 0
Sample values:
0    2023-12-16
1    2023-05-05
2    2023-11-16
3    2023-05-07
4    2023-09-15
Name: last_survey_date, dtype: str

--- last_transaction_date ---
Data type: str
Missing: 0
Sample values:
0    2023-12-05
1    2023-12-18
2    2023-10-27
3    2023-11-30
4    2023-11-17
Name: last_transaction_date, dtype: str

--- first_transaction_date ---
Data type: str
Missing: 0
Sample values:
0    2023-01-05
1    2023-02-05
2    2023-01-31
3    2023-01-10
4    2023-01-05
Name: first_transaction_date, dtype: str

In [25]:
for col in date_columns:
    converted = pd.to_datetime(customer_df[col], errors="coerce")
    
    print(f"{col}:")
    print("Invalid dates:", converted.isna().sum())
    print("Min date:", converted.min())
    print("Max date:", converted.max())
    print()

first_tx:
Invalid dates: 0
Min date: 2023-01-04 00:00:00
Max date: 2023-08-10 00:00:00

last_tx:
Invalid dates: 0
Min date: 2023-05-11 00:00:00
Max date: 2023-12-29 00:00:00

last_survey_date:
Invalid dates: 0
Min date: 2023-01-01 00:00:00
Max date: 2023-12-31 00:00:00

last_transaction_date:
Invalid dates: 0
Min date: 2023-05-11 00:00:00
Max date: 2023-12-29 00:00:00

first_transaction_date:
Invalid dates: 0
Min date: 2023-01-04 00:00:00
Max date: 2023-08-10 00:00:00

In [26]:
first_date = pd.to_datetime(customer_df["first_transaction_date"])
last_date = pd.to_datetime(customer_df["last_transaction_date"])

invalid_date_order = customer_df[first_date > last_date]

print("Invalid date order records:", len(invalid_date_order))

Invalid date order records: 0

In [27]:
print(
    "first_tx == first_transaction_date:",
    (
        customer_df["first_tx"]
        == customer_df["first_transaction_date"]
    ).all()
)

print(
    "last_tx == last_transaction_date:",
    (
        customer_df["last_tx"]
        == customer_df["last_transaction_date"]
    ).all()
)

first_tx == first_transaction_date: True
last_tx == last_transaction_date: False

In [28]:
last_tx_compare = pd.DataFrame({
    "last_tx": customer_df["last_tx"],
    "last_transaction_date": customer_df["last_transaction_date"]
})

last_tx_compare["same"] = (
    last_tx_compare["last_tx"] ==
    last_tx_compare["last_transaction_date"]
)

last_tx_compare["same"].value_counts()

same
False    46989
True      1734
Name: count, dtype: int64

In [29]:
last_tx_compare[
    last_tx_compare["same"] == False
].head(20)

       last_tx last_transaction_date   same
0   2023-12-25            2023-12-05  False
1   2023-12-20            2023-12-18  False
2   2023-12-12            2023-10-27  False
3   2023-12-24            2023-11-30  False
4   2023-11-27            2023-11-17  False
5   2023-11-29            2023-12-28  False
6   2023-12-19            2023-10-26  False
7   2023-12-26            2023-11-21  False
8   2023-12-29            2023-12-16  False
9   2023-12-12            2023-12-20  False
10  2023-12-28            2023-11-20  False
11  2023-11-18            2023-12-29  False
12  2023-12-01            2023-12-24  False
13  2023-12-24            2023-12-29  False
14  2023-12-10            2023-12-29  False
16  2023-12-22            2023-12-26  False
17  2023-12-13            2023-12-02  False
18  2023-12-19            2023-12-16  False
19  2023-12-10            2023-11-15  False
22  2023-12-25            2023-12-26  False

In [30]:
transaction_df.head()

   customer_id        date   amount        type
0     93716481  2023-11-23  1262800    Transfer
1     93716481  2023-01-05   928900  Withdrawal
2     93716481  2023-11-05  1683100     Payment
3     93716481  2023-04-14  4507350     Payment
4     93716481  2023-08-04  2096150     Payment

In [31]:
transaction_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3159157 entries, 0 to 3159156
Data columns (total 4 columns):
 #   Column       Dtype
---  ------       -----
 0   customer_id  int64
 1   date         str
 2   amount       int64
 3   type         str
dtypes: int64(2), str(2)
memory usage: 96.4 MB

In [32]:
transaction_date = pd.to_datetime(
    transaction_df["date"],
    errors="coerce"
)

print("Invalid transaction dates:", transaction_date.isna().sum())
print("Minimum transaction date:", transaction_date.min())
print("Maximum transaction date:", transaction_date.max())

Invalid transaction dates: 0
Minimum transaction date: 2023-01-04 00:00:00
Maximum transaction date: 2023-12-29 00:00:00

In [33]:
actual_last_tx = (
    transaction_df
    .assign(transaction_date=transaction_date)
    .groupby("customer_id")["transaction_date"]
    .max()
    .reset_index()
)

actual_last_tx.columns = [
    "customer_id",
    "actual_last_transaction_date"
]

actual_last_tx.head()

   customer_id actual_last_transaction_date
0     10000617                   2023-12-05
1     10003212                   2023-12-18
2     10004554                   2023-10-27
3     10008981                   2023-11-30
4     10011329                   2023-11-17

In [34]:
date_comparison = customer_df[
    ["customer_id", "last_tx", "last_transaction_date"]
].copy()

date_comparison["last_tx"] = pd.to_datetime(
    date_comparison["last_tx"]
)

date_comparison["last_transaction_date"] = pd.to_datetime(
    date_comparison["last_transaction_date"]
)

date_comparison = date_comparison.merge(
    actual_last_tx,
    on="customer_id",
    how="left"
)

date_comparison.head()

   customer_id    last_tx last_transaction_date actual_last_transaction_date
0     93716481 2023-12-25            2023-12-05                   2023-12-25
1     49020929 2023-12-20            2023-12-18                   2023-12-20
2     52690950 2023-12-12            2023-10-27                   2023-12-12
3     23199751 2023-12-24            2023-11-30                   2023-12-24
4     61997066 2023-11-27            2023-11-17                   2023-11-27

In [35]:
print(
    "last_tx matches actual:",
    (
        date_comparison["last_tx"]
        == date_comparison["actual_last_transaction_date"]
    ).sum()
)

print(
    "last_transaction_date matches actual:",
    (
        date_comparison["last_transaction_date"]
        == date_comparison["actual_last_transaction_date"]
    ).sum()
)

last_tx matches actual: 48723
last_transaction_date matches actual: 1734

In [36]:
actual_first_tx = (
    transaction_df
    .assign(transaction_date=pd.to_datetime(transaction_df["date"]))
    .groupby("customer_id")["transaction_date"]
    .min()
    .reset_index()
)

actual_first_tx.columns = [
    "customer_id",
    "actual_first_transaction_date"
]

first_comparison = customer_df[
    ["customer_id", "first_tx", "first_transaction_date"]
].copy()

first_comparison["first_tx"] = pd.to_datetime(
    first_comparison["first_tx"]
)

first_comparison["first_transaction_date"] = pd.to_datetime(
    first_comparison["first_transaction_date"]
)

first_comparison = first_comparison.merge(
    actual_first_tx,
    on="customer_id",
    how="left"
)

print(
    "first_tx matches actual:",
    (
        first_comparison["first_tx"]
        == first_comparison["actual_first_transaction_date"]
    ).sum()
)

print(
    "first_transaction_date matches actual:",
    (
        first_comparison["first_transaction_date"]
        == first_comparison["actual_first_transaction_date"]
    ).sum()
)

first_tx matches actual: 48723
first_transaction_date matches actual: 48723

In [37]:
numeric_columns = customer_df.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

numeric_columns

['customer_id',
 'age',
 'household_size',
 'active_products',
 'app_logins_frequency',
 'feature_usage_diversity',
 'credit_utilization_ratio',
 'international_transactions',
 'failed_transactions',
 'tx_count',
 'avg_tx_value',
 'total_tx_volume',
 'base_satisfaction',
 'tx_satisfaction',
 'product_satisfaction',
 'satisfaction_score',
 'nps_score',
 'support_tickets_count',
 'resolved_tickets_ratio',
 'app_store_rating',
 'monthly_transaction_count',
 'average_transaction_value',
 'total_transaction_volume',
 'transaction_frequency',
 'weekend_transaction_ratio',
 'avg_daily_transactions',
 'customer_tenure',
 'churn_probability',
 'customer_lifetime_value']

In [38]:
customer_df[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
customer_id,48723.0,5.502799e+07,2.592111e+07,1.000062e+07,3.270835e+07,5.517447e+07,7.724233e+07,9.999980e+07
age,48723.0,4.454494e+01,1.227684e+01,2.900000e+01,3.000000e+01,4.500000e+01,5.900000e+01,6.000000e+01
household_size,48723.0,3.496234e+00,1.583416e+00,1.000000e+00,2.000000e+00,3.000000e+00,4.000000e+00,1.300000e+01
active_products,48723.0,2.095253e+00,1.178333e+00,1.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,5.000000e+00
app_logins_frequency,48723.0,2.237617e+01,1.175071e+01,4.000000e+00,1.500000e+01,2.200000e+01,3.000000e+01,1.000000e+02
feature_usage_diversity,48723.0,2.369538e+00,1.744681e+00,0.000000e+00,1.000000e+00,2.000000e+00,4.000000e+00,1.000000e+01
credit_utilization_ratio,30460.0,2.868762e-01,1.600724e-01,1.794056e-04,1.619276e-01,2.658556e-01,3.909798e-01,9.375464e-01
international_transactions,48723.0,4.939146e-01,7.021834e-01,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,6.000000e+00
failed_transactions,48723.0,1.987562e-01,4.439627e-01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00
tx_count,48723.0,6.483913e+01,6.119342e+02,1.000000e+01,1.200000e+01,1.800000e+01,3.500000e+01,7.746500e+04
avg_tx_value,48723.0,3.564852e+06,3.959443e+06,3.182150e+05,1.339114e+06,1.763107e+06,4.658536e+06,5.167030e+07
total_tx_volume,48723.0,2.574728e+08,6.211110e+09,3.182150e+06,2.015845e+07,4.808115e+07,1.204450e+08,1.073087e+12
base_satisfaction,48723.0,8.001457e+00,9.985988e-01,4.250062e+00,7.325575e+00,8.005452e+00,8.676325e+00,1.193721e+01
tx_satisfaction,48723.0,1.772458e-01,2.169632e-01,5.000000e-02,6.000000e-02,9.000000e-02,1.750000e-01,1.000000e+00
product_satisfaction,48723.0,4.736736e-01,2.344574e-01,0.000000e+00,4.000000e-01,4.000000e-01,6.000000e-01,1.000000e+00
satisfaction_score,48723.0,4.162469e+00,5.784730e-01,2.000000e+00,4.000000e+00,4.000000e+00,5.000000e+00,6.000000e+00
nps_score,48723.0,-2.675685e+01,1.256092e+01,-8.000000e+01,-3.400000e+01,-2.800000e+01,-1.900000e+01,2.300000e+01
support_tickets_count,48723.0,9.974550e-01,9.993603e-01,0.000000e+00,0.000000e+00,1.000000e+00,2.000000e+00,7.000000e+00
resolved_tickets_ratio,48723.0,5.061834e-01,4.761853e-01,0.000000e+00,0.000000e+00,5.000000e-01,1.000000e+00,1.000000e+00
app_store_rating,48723.0,4.156302e+00,5.888649e-01,2.000000e+00,4.000000e+00,4.000000e+00,4.500000e+00,5.000000e+00
monthly_transaction_count,48723.0,5.765448e+00,5.096642e+01,1.000000e+00,1.600000e+00,2.000000e+00,3.090909e+00,6.455417e+03
average_transaction_value,48723.0,3.564852e+06,3.959443e+06,3.182150e+05,1.339114e+06,1.763107e+06,4.658536e+06,5.167030e+07
total_transaction_volume,48723.0,2.574728e+08,6.211110e+09,3.182150e+06,2.015845e+07,4.808115e+07,1.204450e+08,1.073087e+12
transaction_frequency,48723.0,1.865574e-01,1.704244e+00,2.785515e-02,4.154303e-02,5.763689e-02,1.031384e-01,2.157799e+02
weekend_transaction_ratio,48723.0,2.828676e-01,1.044426e-01,0.000000e+00,2.142857e-01,2.800000e-01,3.400000e-01,9.090909e-01
avg_daily_transactions,48723.0,1.865574e-01,1.704244e+00,2.785515e-02,4.154303e-02,5.763689e-02,1.031384e-01,2.157799e+02
customer_tenure,48723.0,1.137391e+01,7.195875e-01,4.700000e+00,1.116667e+01,1.163333e+01,1.186667e+01,1.196667e+01
churn_probability,48723.0,3.429222e-01,6.707345e-02,1.143192e-01,3.029380e-01,3.539717e-01,3.927236e-01,5.006407e-01
customer_lifetime_value,48723.0,3.281597e+08,7.926224e+08,0.000000e+00,5.841438e+07,1.296820e+08,2.973559e+08,1.776860e+10

In [39]:
print(
    "avg_tx_value == average_transaction_value:",
    (
        customer_df["avg_tx_value"]
        == customer_df["average_transaction_value"]
    ).all()
)

print(
    "total_tx_volume == total_transaction_volume:",
    (
        customer_df["total_tx_volume"]
        == customer_df["total_transaction_volume"]
    ).all()
)

print(
    "transaction_frequency == avg_daily_transactions:",
    (
        customer_df["transaction_frequency"]
        == customer_df["avg_daily_transactions"]
    ).all()
)

avg_tx_value == average_transaction_value: False
total_tx_volume == total_transaction_volume: False
transaction_frequency == avg_daily_transactions: True

In [40]:
bounded_columns = [
    "credit_utilization_ratio",
    "tx_satisfaction",
    "product_satisfaction",
    "satisfaction_score",
    "resolved_tickets_ratio",
    "app_store_rating",
    "weekend_transaction_ratio",
    "churn_probability"
]

for col in bounded_columns:
    print(f"\n--- {col} ---")
    print("Min:", customer_df[col].min())
    print("Max:", customer_df[col].max())

--- credit_utilization_ratio ---
Min: 0.0001794056359459
Max: 0.9375464170640504

--- tx_satisfaction ---
Min: 0.05
Max: 1.0

--- product_satisfaction ---
Min: 0.0
Max: 1.0

--- satisfaction_score ---
Min: 2
Max: 6

--- resolved_tickets_ratio ---
Min: 0.0
Max: 1.0

--- app_store_rating ---
Min: 2.0
Max: 5.0

--- weekend_transaction_ratio ---
Min: 0.0
Max: 0.9090909090909092

--- churn_probability ---
Min: 0.1143192083797079
Max: 0.5006406867462094

In [41]:
transaction_metrics = [
    "tx_count",
    "avg_tx_value",
    "total_tx_volume",
    "monthly_transaction_count",
    "customer_lifetime_value"
]

for col in transaction_metrics:
    print(f"\n--- {col} ---")
    print(customer_df[col].nlargest(10).to_list())

--- tx_count ---
[77465, 36792, 35499, 27472, 27191, 23972, 23073, 22680, 21437, 20816]

--- avg_tx_value ---
[51670302.777777776, 38257425.0, 36471090.0, 35559500.0, 32525670.588235293, 32094110.0, 31830458.33333333, 31615332.14285714, 30648660.52631579, 30475968.181818184]

--- total_tx_volume ---
[1073087373150, 511269898750, 381072706550, 377581503150, 297498281300, 98863794550, 82763065250, 70534988700, 67431149750, 55904605100]

--- monthly_transaction_count ---
[6455.416666666667, 3066.0, 2958.25, 2289.333333333333, 2265.9166666666665, 1997.6666666666667, 1922.75, 1890.0, 1786.4166666666667, 1734.6666666666667]

--- customer_lifetime_value ---
[17768601885.674095, 17661493651.548344, 17508150435.39772, 17196321810.412212, 16947840608.422108, 16761066972.659803, 16330521369.1246, 15702331692.186018, 15645040906.431808, 15577760594.17352]

In [42]:
outlier_columns = [
    "age",
    "household_size",
    "active_products",
    "app_logins_frequency",
    "international_transactions",
    "failed_transactions",
    "tx_count",
    "avg_tx_value",
    "total_tx_volume",
    "support_tickets_count",
    "monthly_transaction_count",
    "average_transaction_value",
    "total_transaction_volume",
    "avg_daily_transactions",
    "customer_tenure",
    "customer_lifetime_value"
]

outlier_summary = []

for col in outlier_columns:
    Q1 = customer_df[col].quantile(0.25)
    Q3 = customer_df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = customer_df[
        (customer_df[col] < lower_bound) |
        (customer_df[col] > upper_bound)
    ]
    
    outlier_summary.append({
        "Column": col,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "Lower_Bound": lower_bound,
        "Upper_Bound": upper_bound,
        "Outlier_Count": len(outliers),
        "Outlier_Percentage": round(
            len(outliers) / len(customer_df) * 100, 2
        )
    })

outlier_summary = pd.DataFrame(outlier_summary)

outlier_summary.sort_values(
    "Outlier_Percentage",
    ascending=False
)

,Column,Q1,Q3,IQR,Lower_Bound,Upper_Bound,Outlier_Count,Outlier_Percentage
5,failed_transactions,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8818,18.10
10,monthly_transaction_count,1.600000e+00,3.090909e+00,1.490909e+00,-6.363636e-01,5.327273e+00,6394,13.12
13,avg_daily_transactions,4.154303e-02,1.031384e-01,6.159540e-02,-5.085008e-02,1.955315e-01,5889,12.09
6,tx_count,1.200000e+01,3.500000e+01,2.300000e+01,-2.250000e+01,6.950000e+01,5783,11.87
8,total_tx_volume,2.015845e+07,1.204450e+08,1.002866e+08,-1.302714e+08,2.708748e+08,5379,11.04
12,total_transaction_volume,2.015845e+07,1.204450e+08,1.002866e+08,-1.302714e+08,2.708748e+08,5379,11.04
15,customer_lifetime_value,5.841438e+07,2.973559e+08,2.389415e+08,-2.999979e+08,6.557682e+08,4811,9.87
7,avg_tx_value,1.339114e+06,4.658536e+06,3.319422e+06,-3.640018e+06,9.637669e+06,4602,9.45
11,average_transaction_value,1.339114e+06,4.658536e+06,3.319422e+06,-3.640018e+06,9.637669e+06,4602,9.45
14,customer_tenure,1.116667e+01,1.186667e+01,7.000000e-01,1.011667e+01,1.291667e+01,3248,6.67
3,app_logins_frequency,1.500000e+01,3.000000e+01,1.500000e+01,-7.500000e+00,5.250000e+01,783,1.61
1,household_size,2.000000e+00,4.000000e+00,2.000000e+00,-1.000000e+00,7.000000e+00,701,1.44
4,international_transactions,0.000000e+00,1.000000e+00,1.000000e+00,-1.500000e+00,2.500000e+00,663,1.36
9,support_tickets_count,0.000000e+00,2.000000e+00,2.000000e+00,-3.000000e+00,5.000000e+00,41,0.08
0,age,3.000000e+01,5.900000e+01,2.900000e+01,-1.350000e+01,1.025000e+02,0,0.00
2,active_products,1.000000e+00,3.000000e+00,2.000000e+00,-2.000000e+00,6.000000e+00,0,0.00

In [43]:
cols = [
    "customer_id",
    "tx_count",
    "avg_tx_value",
    "total_tx_volume",
    "monthly_transaction_count",
    "avg_daily_transactions",
    "customer_lifetime_value",
    "customer_segment",
    "clv_segment",
    "last_tx"
]

customer_df.nlargest(10, "tx_count")[cols]

,customer_id,tx_count,avg_tx_value,total_tx_volume,monthly_transaction_count,avg_daily_transactions,customer_lifetime_value,customer_segment,clv_segment,last_tx
4851,87831169,77465,1.385254e+07,1073087373150,1.250000,0.031949,0.000000,power,Platinum,2023-12-29
24010,41089287,36792,1.389622e+07,511269898750,1.818182,0.057803,48.024373,power,Platinum,2023-12-29
30155,10435643,35499,5.685891e+05,20184344600,1.625000,0.053942,8.682129,inactive,Platinum,2023-12-29
8852,79060117,27472,1.374423e+07,377581503150,1.111111,0.033333,15779.931558,power,Platinum,2023-12-29
854,20318435,27191,1.401466e+07,381072706550,7.500000,0.254237,18808.192075,power,Platinum,2023-12-29
3631,89007515,23972,1.631617e+06,39113116600,1.833333,0.032353,29646.320863,occasional,Platinum,2023-12-29
20365,76469096,23073,1.621879e+06,37421625650,8.083333,0.277143,51495.767424,occasional,Platinum,2023-12-29
22714,18934638,22680,1.617430e+06,36683310800,1.666667,0.045249,64907.740842,occasional,Platinum,2023-12-29
33757,87515629,21437,1.387779e+07,297498281300,2.363636,0.076923,646614.746768,power,Platinum,2023-12-29
27584,41099208,20816,4.749414e+06,98863794550,1.555556,0.043614,500095.867158,regular,Platinum,2023-12-29

In [44]:
customer_df.nlargest(10, "customer_lifetime_value")[cols]

,customer_id,tx_count,avg_tx_value,total_tx_volume,monthly_transaction_count,avg_daily_transactions,customer_lifetime_value,customer_segment,clv_segment,last_tx
36518,18841586,1512,1.443447e+07,21824920000,1.333333,0.033994,1.776860e+10,power,Platinum,2023-12-29
11363,80770961,1890,1.419064e+07,26820311150,1.500000,0.045113,1.766149e+10,power,Platinum,2023-12-29
7876,31609413,2103,1.398698e+07,29414624500,1.500000,0.035821,1.750815e+10,power,Platinum,2023-12-29
5861,50871515,2019,1.350281e+07,27262179050,1.333333,0.035608,1.719632e+10,power,Platinum,2023-12-29
34864,32075333,1338,1.431396e+07,19152076300,1.833333,0.033639,1.694784e+10,power,Platinum,2023-12-29
45406,29744689,2536,1.424420e+07,36123303800,4.416667,0.150568,1.676107e+10,power,Platinum,2023-12-29
1270,39980263,1376,1.393667e+07,19176859900,2.000000,0.053254,1.633052e+10,power,Platinum,2023-12-29
40278,12822626,1188,1.347239e+07,16005197850,1.250000,0.034483,1.570233e+10,power,Platinum,2023-12-29
20241,73978441,1231,1.372040e+07,16889811600,1.700000,0.051988,1.564504e+10,power,Platinum,2023-12-29
14041,57185226,999,1.414747e+07,14133325100,1.571429,0.034483,1.557776e+10,power,Platinum,2023-12-29

In [45]:
customer_df["failed_transactions"].value_counts().sort_index()

failed_transactions
0    39905
1     8004
2      766
3       44
4        4
Name: count, dtype: int64

In [46]:
top_tx_customers = customer_df.nlargest(
    10, "tx_count"
)["customer_id"]

raw_transaction_check = (
    transaction_df[
        transaction_df["customer_id"].isin(top_tx_customers)
    ]
    .groupby("customer_id")
    .agg(
        actual_tx_count=("customer_id", "size"),
        actual_total_volume=("amount", "sum"),
        actual_avg_tx_value=("amount", "mean")
    )
    .reset_index()
)

raw_transaction_check

   customer_id  actual_tx_count  actual_total_volume  actual_avg_tx_value
0     10435643            35499          20184344600         5.685891e+05
1     18934638            22680          36683310800         1.617430e+06
2     20318435            27191         381072706550         1.401466e+07
3     41089287            36792         511269898750         1.389622e+07
4     41099208            20816          98863794550         4.749414e+06
5     76469096            23073          37421625650         1.621879e+06
6     79060117            27472         377581503150         1.374423e+07
7     87515629            21437         297498281300         1.387779e+07
8     87831169            77465        1073087373150         1.385254e+07
9     89007515            23972          39113116600         1.631617e+06

In [47]:
customer_transaction_check = customer_df[
    [
        "customer_id",
        "tx_count",
        "avg_tx_value",
        "total_tx_volume",
        "customer_lifetime_value",
        "monthly_transaction_count",
        "avg_daily_transactions"
    ]
].copy()

customer_transaction_check = customer_transaction_check[
    customer_transaction_check["customer_id"].isin(top_tx_customers)
]

customer_transaction_check.merge(
    raw_transaction_check,
    on="customer_id",
    how="left"
)

,customer_id,tx_count,avg_tx_value,total_tx_volume,customer_lifetime_value,monthly_transaction_count,avg_daily_transactions,actual_tx_count,actual_total_volume,actual_avg_tx_value
0,20318435,27191,1.401466e+07,381072706550,18808.192075,7.500000,0.254237,27191,381072706550,1.401466e+07
1,89007515,23972,1.631617e+06,39113116600,29646.320863,1.833333,0.032353,23972,39113116600,1.631617e+06
2,87831169,77465,1.385254e+07,1073087373150,0.000000,1.250000,0.031949,77465,1073087373150,1.385254e+07
3,79060117,27472,1.374423e+07,377581503150,15779.931558,1.111111,0.033333,27472,377581503150,1.374423e+07
4,76469096,23073,1.621879e+06,37421625650,51495.767424,8.083333,0.277143,23073,37421625650,1.621879e+06
5,18934638,22680,1.617430e+06,36683310800,64907.740842,1.666667,0.045249,22680,36683310800,1.617430e+06
6,41089287,36792,1.389622e+07,511269898750,48.024373,1.818182,0.057803,36792,511269898750,1.389622e+07
7,41099208,20816,4.749414e+06,98863794550,500095.867158,1.555556,0.043614,20816,98863794550,4.749414e+06
8,10435643,35499,5.685891e+05,20184344600,8.682129,1.625000,0.053942,35499,20184344600,5.685891e+05
9,87515629,21437,1.387779e+07,297498281300,646614.746768,2.363636,0.076923,21437,297498281300,1.387779e+07

In [48]:
comparison = customer_df[
    [
        "customer_id",
        "avg_tx_value",
        "average_transaction_value",
        "total_tx_volume",
        "total_transaction_volume"
    ]
].copy()

comparison["avg_tx_difference"] = (
    comparison["avg_tx_value"]
    - comparison["average_transaction_value"]
)

comparison["volume_difference"] = (
    comparison["total_tx_volume"]
    - comparison["total_transaction_volume"]
)

comparison.head(10)

,customer_id,avg_tx_value,average_transaction_value,total_tx_volume,total_transaction_volume,avg_tx_difference,volume_difference
0,93716481,1.679872e+06,6.054025e+06,127670300,60540250,-4.374153e+06,67130050
1,49020929,5.445810e+06,2.127414e+06,54458100,23401550,3.318396e+06,31056550
2,52690950,6.403350e+05,3.575915e+06,6403350,35759150,-2.935580e+06,-29355800
3,23199751,6.601804e+05,1.513354e+06,15184150,21186950,-8.531731e+05,-6002800
4,61997066,1.457447e+07,6.126737e+05,262340450,11640800,1.396180e+07,250699650
5,85721098,5.736533e+05,4.092477e+06,8604800,61387150,-3.518823e+06,-52782350
6,97779724,4.778917e+05,1.969662e+06,11469400,25605600,-1.491770e+06,-14136200
7,65536017,4.607239e+06,5.264471e+06,207325750,63173650,-6.572319e+05,144152100
8,22020116,5.801825e+05,1.695647e+06,77744450,25434700,-1.115464e+06,52309750
9,14024733,1.627340e+07,1.698612e+06,211554250,96820900,1.457479e+07,114733350

In [49]:
print(
    "Average transaction value differences:",
    (comparison["avg_tx_difference"] != 0).sum()
)

print(
    "Total transaction volume differences:",
    (comparison["volume_difference"] != 0).sum()
)

Average transaction value differences: 48722
Total transaction volume differences: 48722

In [50]:
comparison[
    ["avg_tx_difference", "volume_difference"]
].describe()

       avg_tx_difference  volume_difference
count       4.872300e+04       4.872300e+04
mean        1.223337e-12       0.000000e+00
std         5.593963e+06       8.786259e+09
min        -5.096634e+07      -1.073059e+12
25%        -2.339940e+06      -6.005062e+07
50%         2.888447e+03       1.911500e+05
75%         2.318008e+06       6.088460e+07
max         5.025353e+07       1.073069e+12

In [51]:
raw_metrics = (
    transaction_df
    .groupby("customer_id")
    .agg(
        raw_tx_count=("amount", "size"),
        raw_avg_tx_value=("amount", "mean"),
        raw_total_tx_volume=("amount", "sum")
    )
    .reset_index()
)

raw_metrics.head()

   customer_id  raw_tx_count  raw_avg_tx_value  raw_total_tx_volume
0     10000617            10      6.054025e+06             60540250
1     10003212            11      2.127414e+06             23401550
2     10004554            10      3.575915e+06             35759150
3     10008981            14      1.513354e+06             21186950
4     10011329            19      6.126737e+05             11640800

In [52]:
metric_validation = customer_df[
    [
        "customer_id",
        "tx_count",
        "avg_tx_value",
        "total_tx_volume",
        "average_transaction_value",
        "total_transaction_volume"
    ]
].merge(
    raw_metrics,
    on="customer_id",
    how="left"
)

In [53]:
print(
    "avg_tx_value matches raw:",
    (
        np.isclose(
            metric_validation["avg_tx_value"],
            metric_validation["raw_avg_tx_value"]
        )
    ).sum()
)

print(
    "average_transaction_value matches raw:",
    (
        np.isclose(
            metric_validation["average_transaction_value"],
            metric_validation["raw_avg_tx_value"]
        )
    ).sum()
)

print(
    "total_tx_volume matches raw:",
    (
        metric_validation["total_tx_volume"]
        == metric_validation["raw_total_tx_volume"]
    ).sum()
)

print(
    "total_transaction_volume matches raw:",
    (
        metric_validation["total_transaction_volume"]
        == metric_validation["raw_total_tx_volume"]
    ).sum()
)

avg_tx_value matches raw: 48723
average_transaction_value matches raw: 1
total_tx_volume matches raw: 48723
total_transaction_volume matches raw: 1

In [54]:
transaction_df["date"] = pd.to_datetime(transaction_df["date"])

frequency_check = (
    transaction_df
    .groupby("customer_id")
    .agg(
        actual_tx_count=("customer_id", "size"),
        first_date=("date", "min"),
        last_date=("date", "max")
    )
    .reset_index()
)

frequency_check["active_days"] = (
    frequency_check["last_date"]
    - frequency_check["first_date"]
).dt.days + 1

frequency_check["calculated_avg_daily_transactions"] = (
    frequency_check["actual_tx_count"]
    / frequency_check["active_days"]
)

frequency_check.head()

,customer_id,actual_tx_count,first_date,last_date,active_days,calculated_avg_daily_transactions
0,10000617,10,2023-01-14,2023-12-05,326,0.030675
1,10003212,11,2023-01-18,2023-12-18,335,0.032836
2,10004554,10,2023-04-10,2023-10-27,201,0.049751
3,10008981,14,2023-02-10,2023-11-30,294,0.047619
4,10011329,19,2023-01-14,2023-11-17,308,0.061688

In [55]:
frequency_validation = customer_df[
    [
        "customer_id",
        "tx_count",
        "monthly_transaction_count",
        "avg_daily_transactions"
    ]
].merge(
    frequency_check[
        [
            "customer_id",
            "actual_tx_count",
            "active_days",
            "calculated_avg_daily_transactions"
        ]
    ],
    on="customer_id",
    how="left"
)

frequency_validation.head(10)

,customer_id,tx_count,monthly_transaction_count,avg_daily_transactions,actual_tx_count,active_days,calculated_avg_daily_transactions
0,93716481,76,1.428571,0.030769,76,355,0.214085
1,49020929,10,1.571429,0.032934,10,319,0.031348
2,52690950,10,2.500000,0.050000,10,316,0.031646
3,23199751,23,1.555556,0.047782,23,349,0.065903
4,61997066,18,2.111111,0.061889,18,327,0.055046
5,85721098,15,1.363636,0.042373,15,305,0.049180
6,97779724,24,2.166667,0.045614,24,338,0.071006
7,65536017,45,1.714286,0.038710,45,353,0.127479
8,22020116,134,1.875000,0.046154,134,359,0.373259
9,14024733,13,5.181818,0.166181,13,283,0.045936

In [56]:
print(
    "avg_daily_transactions matching our calculation:",
    np.isclose(
        frequency_validation["avg_daily_transactions"],
        frequency_validation["calculated_avg_daily_transactions"],
        rtol=1e-5,
        atol=1e-8
    ).sum()
)

avg_daily_transactions matching our calculation: 23

In [57]:
clv_columns = [
    "customer_lifetime_value",
    "tx_count",
    "avg_tx_value",
    "total_tx_volume",
    "customer_tenure",
    "active_products",
    "satisfaction_score",
    "churn_probability"
]

customer_df[clv_columns].corr()["customer_lifetime_value"].sort_values(
    ascending=False
)

customer_lifetime_value    1.000000
avg_tx_value               0.343133
tx_count                   0.163954
total_tx_volume            0.107269
satisfaction_score         0.055261
active_products            0.001241
customer_tenure           -0.003453
churn_probability         -0.020342
Name: customer_lifetime_value, dtype: float64

In [58]:
print(
    "CLV = 0:",
    (customer_df["customer_lifetime_value"] == 0).sum()
)

print(
    "CLV missing:",
    customer_df["customer_lifetime_value"].isna().sum()
)

CLV = 0: 1
CLV missing: 0

In [59]:
customer_df[
    customer_df["customer_lifetime_value"] == 0
][[
    "customer_id",
    "tx_count",
    "avg_tx_value",
    "total_tx_volume",
    "customer_tenure",
    "customer_segment",
    "clv_segment"
]].head(10)

,customer_id,tx_count,avg_tx_value,total_tx_volume,customer_tenure,customer_segment,clv_segment
4851,87831169,77465,1.385254e+07,1073087373150,11.1,power,Platinum

In [60]:
missing_columns = [
    "complaint_topics",
    "credit_utilization_ratio",
    "feature_requests"
]

for col in missing_columns:
    print(f"\n========== {col} ==========")
    
    missing_mask = customer_df[col].isna()
    
    print("Missing:", missing_mask.sum())
    print("Available:", (~missing_mask).sum())
    
    print("\nCustomer segment:")
    print(
        pd.crosstab(
            missing_mask,
            customer_df["customer_segment"],
            normalize="index"
        ).round(3)
    )

========== complaint_topics ==========
Missing: 24346
Available: 24377

Customer segment:
customer_segment  inactive  occasional  power  regular
complaint_topics
False                0.205       0.394    0.1    0.300
True                 0.201       0.402    0.1    0.298

========== credit_utilization_ratio ==========
Missing: 18263
Available: 30460

Customer segment:
customer_segment          inactive  occasional  power  regular
credit_utilization_ratio
False                        0.205       0.394  0.101    0.300
True                         0.201       0.404  0.098    0.297

========== feature_requests ==========
Missing: 16115
Available: 32608

Customer segment:
customer_segment  inactive  occasional  power  regular
feature_requests
False                0.206       0.398    0.1    0.297
True                 0.198       0.399    0.1    0.303

In [61]:
for col in missing_columns:
    print(f"\n========== {col} ==========")
    
    missing_mask = customer_df[col].isna()
    
    comparison = customer_df.groupby(missing_mask)[
        [
            "tx_count",
            "total_tx_volume",
            "avg_tx_value",
            "support_tickets_count",
            "satisfaction_score",
            "churn_probability"
        ]
    ].mean()
    
    comparison.index = ["Available", "Missing"]
    
    display(comparison.round(2))

========== complaint_topics ==========

,tx_count,total_tx_volume,avg_tx_value,support_tickets_count,satisfaction_score,churn_probability
Available,65.65,2.594405e+08,3570697.78,1.0,4.16,0.34
Missing,64.03,2.555027e+08,3558998.15,1.0,4.16,0.34

========== credit_utilization_ratio ==========

,tx_count,total_tx_volume,avg_tx_value,support_tickets_count,satisfaction_score,churn_probability
Available,62.97,2.451874e+08,3582024.33,1.00,4.19,0.34
Missing,67.95,2.779632e+08,3536210.24,0.99,4.12,0.34

========== feature_requests ==========

,tx_count,total_tx_volume,avg_tx_value,support_tickets_count,satisfaction_score,churn_probability
Available,64.96,2.667889e+08,3560862.55,1.0,4.16,0.34
Missing,64.59,2.386223e+08,3572923.52,1.0,4.16,0.34

In [62]:
for col in missing_columns:
    missing_mask = customer_df[col].isna()
    
    result = customer_df.groupby(missing_mask)[
        "churn_probability"
    ].mean()
    
    result.index = ["Available", "Missing"]
    
    print(f"\n{col}")
    print(result.round(4))

complaint_topics
Available    0.3430
Missing      0.3429
Name: churn_probability, dtype: float64

credit_utilization_ratio
Available    0.3445
Missing      0.3403
Name: churn_probability, dtype: float64

feature_requests
Available    0.3432
Missing      0.3423
Name: churn_probability, dtype: float64

In [63]:
customer_clean = customer_df.copy()

In [64]:
date_columns_to_convert = [
    "first_tx",
    "last_tx",
    "last_survey_date"
]

for col in date_columns_to_convert:
    customer_clean[col] = pd.to_datetime(
        customer_clean[col],
        errors="coerce"
    )

In [65]:
customer_clean["complaint_topics"] = (
    customer_clean["complaint_topics"]
    .fillna("No Complaint Recorded")
)

customer_clean["feature_requests"] = (
    customer_clean["feature_requests"]
    .fillna("No Feature Request")
)

In [66]:
customer_clean["credit_utilization_missing"] = (
    customer_clean["credit_utilization_ratio"]
    .isna()
    .astype(int)
)

In [67]:
columns_to_remove = [
    "first_transaction_date",
    "last_transaction_date",
    "transaction_frequency",
    "average_transaction_value",
    "total_transaction_volume"
]

customer_clean = customer_clean.drop(
    columns=columns_to_remove
)

In [70]:
output_path = r"D:\Customer_Churn_Retention_Analysis\02_ Clean_Data\customer_data_clean.csv"

customer_clean.to_csv(
    output_path,
    index=False
)

print("Clean dataset saved successfully!")
print(output_path)

Clean dataset saved successfully!
D:\Customer_Churn_Retention_Analysis\02_ Clean_Data\customer_data_clean.csv

In [71]:
import os

print(os.path.exists(output_path))

True

In [72]:
print("Original shape:", customer_df.shape)
print("Clean shape:", customer_clean.shape)

Original shape: (48723, 54)
Clean shape: (48723, 50)

In [73]:
customer_clean.isna().sum().sort_values(
    ascending=False
).head(10)

credit_utilization_ratio    18263
customer_id                     0
gender                          0
location                        0
income_bracket                  0
occupation                      0
education_level                 0
marital_status                  0
household_size                  0
acquisition_channel             0
dtype: int64

In [74]:
print(
    "Duplicate rows:",
    customer_clean.duplicated().sum()
)

print(
    "Duplicate customer IDs:",
    customer_clean["customer_id"].duplicated().sum()
)

Duplicate rows: 0
Duplicate customer IDs: 0

## Plan 2- Churn Analysis

In [78]:
transaction_df["date"] = pd.to_datetime(transaction_df["date"])

print("Minimum transaction date:",
      transaction_df["date"].min())

print("Maximum transaction date:",
      transaction_df["date"].max())

Minimum transaction date: 2023-01-04 00:00:00
Maximum transaction date: 2023-12-29 00:00:00

In [79]:
print(
    "Customer first transaction:",
    customer_clean["first_tx"].min()
)

print(
    "Customer last transaction:",
    customer_clean["last_tx"].max()
)

Customer first transaction: 2023-01-04 00:00:00
Customer last transaction: 2023-12-29 00:00:00

In [80]:
analysis_end_date = transaction_df["date"].max()

customer_clean["recency_days"] = (
    analysis_end_date - customer_clean["last_tx"]
).dt.days

customer_clean["recency_days"].describe()

count    48723.000000
mean        17.743653
std         21.702633
min          0.000000
25%          3.000000
50%         10.000000
75%         24.000000
max        232.000000
Name: recency_days, dtype: float64

In [81]:
bins = [-1, 30, 60, 90, float("inf")]
labels = [
    "Active (0-30 days)",
    "At Risk (31-60 days)",
    "High Risk (61-90 days)",
    "Inactive (90+ days)"
]

customer_clean["recency_band"] = pd.cut(
    customer_clean["recency_days"],
    bins=bins,
    labels=labels
)

customer_clean["recency_band"].value_counts().sort_index()

recency_band
Active (0-30 days)        39378
At Risk (31-60 days)       6696
High Risk (61-90 days)     1896
Inactive (90+ days)         753
Name: count, dtype: int64

In [82]:
customer_clean["recency_band"].value_counts(
    normalize=True
).sort_index().mul(100).round(2)

recency_band
Active (0-30 days)        80.82
At Risk (31-60 days)      13.74
High Risk (61-90 days)     3.89
Inactive (90+ days)        1.55
Name: proportion, dtype: float64

In [83]:
monthly_activity = (
    transaction_df
    .assign(month=transaction_df["date"].dt.to_period("M"))
    .groupby("month")["customer_id"]
    .nunique()
    .reset_index(name="active_customers")
)

monthly_activity

      month  active_customers
0   2023-01             38139
1   2023-02             38019
2   2023-03             39404
3   2023-04             38944
4   2023-05             39423
5   2023-06             39023
6   2023-07             39513
7   2023-08             39413
8   2023-09             38992
9   2023-10             39434
10  2023-11             38885
11  2023-12             38532

In [84]:
reference_date = pd.Timestamp("2023-09-30")

future_transactions = transaction_df[
    (transaction_df["date"] > reference_date) &
    (transaction_df["date"] <= analysis_end_date)
]

future_active_customers = set(
    future_transactions["customer_id"].unique()
)

print("Customers with future activity:",
      len(future_active_customers))

Customers with future activity: 47943

In [85]:
customer_clean["churned"] = (
    ~customer_clean["customer_id"].isin(
        future_active_customers
    )
).astype(int)

In [86]:
print(
    customer_clean["churned"].value_counts()
)

print(
    customer_clean["churned"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

churned
0    47943
1      780
Name: count, dtype: int64
churned
0    98.4
1     1.6
Name: proportion, dtype: float64

In [87]:
churned_customers = customer_clean[
    customer_clean["churned"] == 1
]

print("Total initially churned:",
      len(churned_customers))

print("\nFirst transaction date distribution:")
print(
    churned_customers["first_tx"].describe()
)

Total initially churned: 780

First transaction date distribution:
count                           780
mean     2023-01-26 09:19:23.076923
min             2023-01-04 00:00:00
25%             2023-01-11 00:00:00
50%             2023-01-20 00:00:00
75%             2023-02-06 00:00:00
max             2023-04-27 00:00:00
Name: first_tx, dtype: object

In [88]:
print(
    "Churned customers whose first transaction was after reference date:",
    (
        churned_customers["first_tx"] > reference_date
    ).sum()
)

Churned customers whose first transaction was after reference date: 0

In [90]:
churned_customers[
    churned_customers["first_tx"] > reference_date
][
    [
        "customer_id",
        "first_tx",
        "last_tx",
        "recency_days",
        "customer_segment"
    ]
].head(20)

Empty DataFrame
Columns: [customer_id, first_tx, last_tx, recency_days, customer_segment]
Index: []

#### A customer is classified as churned if they had transaction activity before 30 September 2023, but had no transaction from 1 October 2023 through 29 December 2023.

### Plan 3 — Retention KPIs & Customer Segmentation

In [91]:
# ==========================================
# PLAN 3 - STEP 3.1
# Customer Retention KPIs
# ==========================================

total_customers = customer_clean["customer_id"].nunique()

churned_customers_count = (
    customer_clean["churned"] == 1
).sum()

retained_customers_count = (
    customer_clean["churned"] == 0
).sum()

churn_rate = (
    churned_customers_count / total_customers
) * 100

retention_rate = (
    retained_customers_count / total_customers
) * 100


print("Total Customers:", total_customers)
print("Churned Customers:", churned_customers_count)
print("Retained Customers:", retained_customers_count)
print("Churn Rate:", round(churn_rate, 2), "%")
print("Retention Rate:", round(retention_rate, 2), "%")

Total Customers: 48723
Churned Customers: 780
Retained Customers: 47943
Churn Rate: 1.6 %
Retention Rate: 98.4 %

In [92]:
# ==========================================
# PLAN 3 - STEP 3.2
# Transaction Frequency & Customer Value KPIs
# ==========================================

total_transactions = len(transaction_df)

avg_transactions_per_customer = (
    total_transactions / total_customers
)

transactions_per_customer = (
    transaction_df
    .groupby("customer_id")
    .size()
)

repeat_customers = (
    transactions_per_customer >= 2
).sum()

repeat_customer_rate = (
    repeat_customers / total_customers
) * 100

total_spend = transaction_df["amount"].sum()

avg_customer_spend = (
    total_spend / total_customers
)

avg_transaction_value = (
    transaction_df["amount"].mean()
)


print("Total Transactions:", total_transactions)
print(
    "Average Transactions per Customer:",
    round(avg_transactions_per_customer, 2)
)
print("Repeat Customers:", repeat_customers)
print(
    "Repeat Customer Rate:",
    round(repeat_customer_rate, 2),
    "%"
)
print("Total Customer Spend:", round(total_spend, 2))
print(
    "Average Customer Spend:",
    round(avg_customer_spend, 2)
)
print(
    "Average Transaction Value:",
    round(avg_transaction_value, 2)
)

Total Transactions: 3159157
Average Transactions per Customer: 64.84
Repeat Customers: 48723
Repeat Customer Rate: 100.0 %
Total Customer Spend: 12544849568700
Average Customer Spend: 257472847.91
Average Transaction Value: 3970948.44

In [94]:
# Add transaction count to customer-level table

customer_clean = customer_clean.merge(
    transactions_per_customer.rename("transaction_count"),
    on="customer_id",
    how="left"
)

customer_clean.head()

,customer_id,age,gender,location,income_bracket,occupation,education_level,marital_status,household_size,acquisition_channel,...,avg_daily_transactions,customer_tenure,churn_probability,customer_lifetime_value,credit_utilization_missing,recency_days,recency_band,churned,customer_tenure_days,transaction_count
0,93716481,44,Male,"Pereira, Risaralda",Very High,Engineer,Master,Married,5,Partnership,...,0.030769,11.633333,0.362269,3.124148e+08,0,4,Active (0-30 days),0,354,76
1,49020929,44,Male,"Cali, Valle del Cauca",Medium,Construction Worker,Bachelor,Married,2,Paid Ad,...,0.032934,11.500000,0.181790,1.670223e+08,1,9,Active (0-30 days),0,318,10
2,52690950,45,Male,"Barranquilla, Atlántico",High,Construction Worker,Bachelor,Married,4,Paid Ad,...,0.050000,8.766667,0.321265,1.940371e+07,1,17,Active (0-30 days),0,315,10
3,23199751,45,Male,"Bogotá, Cundinamarca",High,Electrician,High School,Single,2,Referral,...,0.047782,10.733333,0.336629,3.597811e+07,1,5,Active (0-30 days),0,348,23
4,61997066,44,Female,"Bogotá, Cundinamarca",Medium,Cleaner,Bachelor,Married,3,Paid Ad,...,0.061889,11.633333,0.398151,3.046620e+08,0,32,At Risk (31-60 days),0,326,18

In [95]:
# ==========================================
# PLAN 3 - STEP 3.3
# Customer Tenure & Transaction Gap
# ==========================================

# Customer tenure
customer_clean["customer_tenure_days"] = (
    customer_clean["last_tx"] - customer_clean["first_tx"]
).dt.days


# Average days between transactions
customer_clean["avg_days_between_transactions"] = (
    customer_clean["customer_tenure_days"] /
    (customer_clean["transaction_count"] - 1)
)


# Transactions per 30 days
customer_clean["transactions_per_30_days"] = (
    customer_clean["transaction_count"] /
    (customer_clean["customer_tenure_days"] / 30)
)


# Check results
customer_clean[
    [
        "customer_id",
        "first_tx",
        "last_tx",
        "transaction_count",
        "customer_tenure_days",
        "avg_days_between_transactions",
        "transactions_per_30_days",
        "recency_days",
        "recency_band",
        "churned"
    ]
].head(10)

,customer_id,first_tx,last_tx,transaction_count,customer_tenure_days,avg_days_between_transactions,transactions_per_30_days,recency_days,recency_band,churned
0,93716481,2023-01-05,2023-12-25,76,354,4.720000,6.440678,4,Active (0-30 days),0
1,49020929,2023-02-05,2023-12-20,10,318,35.333333,0.943396,9,Active (0-30 days),0
2,52690950,2023-01-31,2023-12-12,10,315,35.000000,0.952381,17,Active (0-30 days),0
3,23199751,2023-01-10,2023-12-24,23,348,15.818182,1.982759,5,Active (0-30 days),0
4,61997066,2023-01-05,2023-11-27,18,326,19.176471,1.656442,32,At Risk (31-60 days),0
5,85721098,2023-01-29,2023-11-29,15,304,21.714286,1.480263,30,Active (0-30 days),0
6,97779724,2023-01-16,2023-12-19,24,337,14.652174,2.136499,10,Active (0-30 days),0
7,65536017,2023-01-08,2023-12-26,45,352,8.000000,3.835227,3,Active (0-30 days),0
8,22020116,2023-01-05,2023-12-29,134,358,2.691729,11.229050,0,Active (0-30 days),0
9,14024733,2023-03-05,2023-12-12,13,282,23.500000,1.382979,17,Active (0-30 days),0

In [96]:
# ==========================================
# PLAN 3 - STEP 3.4
# Current Customer Status Distribution
# ==========================================

customer_status_summary = (
    customer_clean["recency_band"]
    .value_counts()
    .reset_index()
)

customer_status_summary.columns = [
    "recency_band",
    "customer_count"
]

customer_status_summary["percentage"] = (
    customer_status_summary["customer_count"]
    / total_customers
) * 100

customer_status_summary

             recency_band  customer_count  percentage
0      Active (0-30 days)           39378   80.820147
1    At Risk (31-60 days)            6696   13.742996
2  High Risk (61-90 days)            1896    3.891386
3     Inactive (90+ days)             753    1.545471

In [99]:
# Yahan ek interesting point hai:
#Current-status Inactive = 753
#while our Historical Observed Churn = 780.
#Ye dono same number hona necessary nahi hai, because they answer different questions.
#753 → Current status:
#29 Dec 2023 ko last transaction se 90+ days inactive.
#780 → Historical observed churn:
#30 Sep 2023 ko active tha, lekin 1 Oct–29 Dec ke observation window mein wapas nahi aaya.
#👉 Exactly isi liye hum dono metrics ko separate rakhenge.

In [100]:
customer_clean["transactions_per_30_days"].describe()

count    48723.000000
mean         5.596722
std         51.127331
min          0.835655
25%          1.246291
50%          1.729107
75%          3.094153
max       6473.398329
Name: transactions_per_30_days, dtype: float64

In [101]:
# Check customers with extremely high transaction frequency

customer_clean[
    [
        "customer_id",
        "transaction_count",
        "customer_tenure_days",
        "avg_days_between_transactions",
        "transactions_per_30_days",
        "recency_days",
        "recency_band"
    ]
].sort_values(
    "transactions_per_30_days",
    ascending=False
).head(10)

,customer_id,transaction_count,customer_tenure_days,avg_days_between_transactions,transactions_per_30_days,recency_days,recency_band
4851,87831169,77465,359,0.004634,6473.398329,0,Active (0-30 days)
24010,41089287,36792,359,0.009758,3074.540390,0,Active (0-30 days)
30155,10435643,35499,359,0.010113,2966.490251,0,Active (0-30 days)
8852,79060117,27472,359,0.013068,2295.710306,0,Active (0-30 days)
854,20318435,27191,359,0.013203,2272.228412,0,Active (0-30 days)
3631,89007515,23972,359,0.014976,2003.231198,0,Active (0-30 days)
20365,76469096,23073,359,0.015560,1928.105850,0,Active (0-30 days)
22714,18934638,22680,359,0.015830,1895.264624,0,Active (0-30 days)
33757,87515629,21437,359,0.016748,1791.392758,0,Active (0-30 days)
27584,41099208,20816,359,0.017247,1739.498607,0,Active (0-30 days)

In [102]:
customer_clean["transaction_count"].describe()

count    48723.000000
mean        64.839131
std        611.934241
min         10.000000
25%         12.000000
50%         18.000000
75%         35.000000
max      77465.000000
Name: transaction_count, dtype: float64

In [103]:
customer_clean["transaction_count"].quantile(
    [0.50, 0.75, 0.90, 0.95, 0.99, 0.999]
)

0.500      18.000
0.750      35.000
0.900      82.000
0.950     150.900
0.990     627.780
0.999    5056.156
Name: transaction_count, dtype: float64

In [104]:
# ==========================================
# PLAN 3 - STEP 3.4
# Customer Frequency Segmentation
# ==========================================

def frequency_segment(transaction_count):
    if transaction_count <= 18:
        return "Low Frequency"
    elif transaction_count <= 35:
        return "Regular Frequency"
    elif transaction_count <= 82:
        return "High Frequency"
    else:
        return "Very High Frequency"


customer_clean["frequency_segment"] = (
    customer_clean["transaction_count"]
    .apply(frequency_segment)
)


# Check distribution
frequency_summary = (
    customer_clean["frequency_segment"]
    .value_counts()
    .reset_index()
)

frequency_summary.columns = [
    "frequency_segment",
    "customer_count"
]

frequency_summary["percentage"] = (
    frequency_summary["customer_count"]
    / total_customers
) * 100

frequency_summary

     frequency_segment  customer_count  percentage
0        Low Frequency           24712   50.719373
1    Regular Frequency           12065   24.762433
2       High Frequency            7132   14.637851
3  Very High Frequency            4814    9.880344

In [105]:
# ==========================================
# PLAN 3 - STEP 3.5
# Current Status × Frequency Segmentation
# ==========================================

status_frequency = pd.crosstab(
    customer_clean["recency_band"],
    customer_clean["frequency_segment"]
)

status_frequency

frequency_segment,High Frequency,Low Frequency,Regular Frequency,Very High Frequency
recency_band,,,,
Active (0-30 days),7027,16831,10706,4814
At Risk (31-60 days),105,5378,1213,0
High Risk (61-90 days),0,1773,123,0
Inactive (90+ days),0,730,23,0

In [106]:
status_frequency_percentage = (
    pd.crosstab(
        customer_clean["recency_band"],
        customer_clean["frequency_segment"],
        normalize="index"
    ) * 100
).round(2)

status_frequency_percentage

frequency_segment,High Frequency,Low Frequency,Regular Frequency,Very High Frequency
recency_band,,,,
Active (0-30 days),17.84,42.74,27.19,12.23
At Risk (31-60 days),1.57,80.32,18.12,0.00
High Risk (61-90 days),0.00,93.51,6.49,0.00
Inactive (90+ days),0.00,96.95,3.05,0.00

In [107]:
# ==========================================
# PLAN 3 - STEP 3.6
# Retention Priority Segmentation
# ==========================================

def retention_priority(row):

    status = row["recency_band"]
    frequency = row["frequency_segment"]

    # Active customers
    if status == "Active (0-30 days)":
        return "Healthy / Maintain"

    # At Risk customers
    elif status == "At Risk (31-60 days)":
        if frequency == "High Frequency":
            return "High Priority"
        elif frequency == "Regular Frequency":
            return "Medium Priority"
        else:
            return "Re-engagement"

    # High Risk customers
    elif status == "High Risk (61-90 days)":
        return "Urgent Re-engagement"

    # Inactive customers
    elif status == "Inactive (90+ days)":
        return "Inactive / Win-back"


customer_clean["retention_priority"] = (
    customer_clean.apply(
        retention_priority,
        axis=1
    )
)


# Summary
retention_priority_summary = (
    customer_clean["retention_priority"]
    .value_counts()
    .reset_index()
)

retention_priority_summary.columns = [
    "retention_priority",
    "customer_count"
]

retention_priority_summary["percentage"] = (
    retention_priority_summary["customer_count"]
    / total_customers
) * 100

retention_priority_summary

     retention_priority  customer_count  percentage
0    Healthy / Maintain           39378   80.820147
1         Re-engagement            5378   11.037908
2  Urgent Re-engagement            1896    3.891386
3       Medium Priority            1213    2.489584
4   Inactive / Win-back             753    1.545471
5         High Priority             105    0.215504

In [109]:
total_spend = transaction_df["amount"].sum()

In [110]:
# ==========================================
# PLAN 3 - STEP 3.7
# Customer Value Features
# ==========================================

customer_spend = (
    transaction_df
    .groupby("customer_id")["amount"]
    .agg(
        total_spend="sum",
        avg_transaction_value="mean"
    )
    .reset_index()
)

customer_clean = customer_clean.merge(
    customer_spend,
    on="customer_id",
    how="left"
)

customer_clean[
    [
        "customer_id",
        "transaction_count",
        "total_spend",
        "avg_transaction_value"
    ]
].head(10)

   customer_id  transaction_count  total_spend  avg_transaction_value
0     93716481                 76    127670300           1.679872e+06
1     49020929                 10     54458100           5.445810e+06
2     52690950                 10      6403350           6.403350e+05
3     23199751                 23     15184150           6.601804e+05
4     61997066                 18    262340450           1.457447e+07
5     85721098                 15      8604800           5.736533e+05
6     97779724                 24     11469400           4.778917e+05
7     65536017                 45    207325750           4.607239e+06
8     22020116                134     77744450           5.801825e+05
9     14024733                 13    211554250           1.627340e+07

In [111]:
customer_clean[
    ["total_spend", "avg_transaction_value"]
].describe()

        total_spend  avg_transaction_value
count  4.872300e+04           4.872300e+04
mean   2.574728e+08           3.564852e+06
std    6.211110e+09           3.959443e+06
min    3.182150e+06           3.182150e+05
25%    2.015845e+07           1.339114e+06
50%    4.808115e+07           1.763107e+06
75%    1.204450e+08           4.658536e+06
max    1.073087e+12           5.167030e+07

In [112]:
customer_clean["total_spend"].quantile(
    [0.25, 0.50, 0.75, 0.90, 0.95, 0.99]
)

0.25    2.015845e+07
0.50    4.808115e+07
0.75    1.204450e+08
0.90    2.983433e+08
0.95    5.735315e+08
0.99    2.416613e+09
Name: total_spend, dtype: float64

In [113]:
# ==========================================
# PLAN 3 - STEP 3.7
# Customer Value Segmentation
# ==========================================

def value_segment(total_spend):
    if total_spend <= 2.015845e7:
        return "Low Value"
    elif total_spend <= 4.808115e7:
        return "Regular Value"
    elif total_spend <= 1.204450e8:
        return "High Value"
    else:
        return "Very High Value"


customer_clean["value_segment"] = (
    customer_clean["total_spend"]
    .apply(value_segment)
)


# Check distribution
value_summary = (
    customer_clean["value_segment"]
    .value_counts()
    .reset_index()
)

value_summary.columns = [
    "value_segment",
    "customer_count"
]

value_summary["percentage"] = (
    value_summary["customer_count"]
    / total_customers
) * 100

value_summary

     value_segment  customer_count  percentage
0  Very High Value           12181   25.000513
1        Low Value           12181   25.000513
2    Regular Value           12181   25.000513
3       High Value           12180   24.998461

In [114]:
# ==========================================
# PLAN 3 - STEP 3.8
# Current Status × Customer Value
# ==========================================

status_value = pd.crosstab(
    customer_clean["recency_band"],
    customer_clean["value_segment"]
)

status_value

value_segment           High Value  Low Value  Regular Value  Very High Value
recency_band
Active (0-30 days)           10044       8560           9547            11227
At Risk (31-60 days)          1567       2453           1949              727
High Risk (61-90 days)         408        788            528              172
Inactive (90+ days)            161        380            157               55

In [115]:
status_value_percentage = (
    pd.crosstab(
        customer_clean["recency_band"],
        customer_clean["value_segment"],
        normalize="index"
    ) * 100
).round(2)

status_value_percentage

value_segment           High Value  Low Value  Regular Value  Very High Value
recency_band
Active (0-30 days)           25.51      21.74          24.24            28.51
At Risk (31-60 days)         23.40      36.63          29.11            10.86
High Risk (61-90 days)       21.52      41.56          27.85             9.07
Inactive (90+ days)          21.38      50.46          20.85             7.30

In [116]:
# ==========================================
# PLAN 3 - STEP 3.9
# RFM-style Customer Combination
# ==========================================

rfm_summary = (
    customer_clean
    .groupby(
        [
            "recency_band",
            "frequency_segment",
            "value_segment"
        ]
    )
    .agg(
        customer_count=("customer_id", "nunique"),
        total_spend=("total_spend", "sum"),
        avg_spend=("total_spend", "mean")
    )
    .reset_index()
    .sort_values(
        "customer_count",
        ascending=False
    )
)

rfm_summary.head(20)

,recency_band,frequency_segment,value_segment,customer_count,total_spend,avg_spend
5,Active (0-30 days),Low Frequency,Low Value,6392,74762619250,1.169628e+07
6,Active (0-30 days),Low Frequency,Regular Value,4870,142908189250,2.934460e+07
14,Active (0-30 days),Very High Frequency,Very High Value,4152,8941258601900,2.153482e+09
4,Active (0-30 days),Low Frequency,High Value,4069,288626637000,7.093306e+07
10,Active (0-30 days),Regular Frequency,Regular Value,3316,121348837150,3.659494e+07
3,Active (0-30 days),High Frequency,Very High Value,3081,1072610341900,3.481371e+08
8,Active (0-30 days),Regular Frequency,High Value,2819,230145213600,8.164073e+07
0,Active (0-30 days),High Frequency,High Value,2524,204966845000,8.120715e+07
11,Active (0-30 days),Regular Frequency,Very High Value,2494,581781782450,2.332726e+08
20,At Risk (31-60 days),Low Frequency,Low Value,2198,26109689050,1.187884e+07
9,Active (0-30 days),Regular Frequency,Low Value,2077,29241968050,1.407894e+07
21,At Risk (31-60 days),Low Frequency,Regular Value,1502,45732615700,3.044781e+07
7,Active (0-30 days),Low Frequency,Very High Value,1500,291812891600,1.945419e+08
2,Active (0-30 days),High Frequency,Regular Value,1331,40661364550,3.054949e+07
19,At Risk (31-60 days),Low Frequency,High Value,1231,84644037750,6.876039e+07
28,High Risk (61-90 days),Low Frequency,Low Value,763,9098001400,1.192399e+07
12,Active (0-30 days),Very High Frequency,High Value,632,46302314050,7.326316e+07
29,High Risk (61-90 days),Low Frequency,Regular Value,483,14775796150,3.059171e+07
22,At Risk (31-60 days),Low Frequency,Very High Value,447,85072175000,1.903181e+08
25,At Risk (31-60 days),Regular Frequency,Regular Value,429,15266732350,3.558679e+07

In [117]:
# ==========================================
# PLAN 3 - STEP 3.10
# RFM Segmentation vs Historical Churn
# ==========================================

rfm_churn_summary = (
    customer_clean
    .groupby(
        [
            "recency_band",
            "frequency_segment",
            "value_segment"
        ]
    )
    .agg(
        customers=("customer_id", "nunique"),
        churned_customers=("churned", "sum")
    )
    .reset_index()
)

rfm_churn_summary["observed_churn_rate"] = (
    rfm_churn_summary["churned_customers"]
    / rfm_churn_summary["customers"]
) * 100

rfm_churn_summary = (
    rfm_churn_summary
    .sort_values(
        "observed_churn_rate",
        ascending=False
    )
)

rfm_churn_summary.head(20)

,recency_band,frequency_segment,value_segment,customers,churned_customers,observed_churn_rate
37,Inactive (90+ days),Low Frequency,Regular Value,149,149,100.000000
36,Inactive (90+ days),Low Frequency,Low Value,376,376,100.000000
35,Inactive (90+ days),Low Frequency,High Value,155,155,100.000000
42,Inactive (90+ days),Regular Frequency,Very High Value,5,5,100.000000
41,Inactive (90+ days),Regular Frequency,Regular Value,8,8,100.000000
40,Inactive (90+ days),Regular Frequency,Low Value,4,4,100.000000
39,Inactive (90+ days),Regular Frequency,High Value,6,6,100.000000
38,Inactive (90+ days),Low Frequency,Very High Value,50,50,100.000000
33,High Risk (61-90 days),Regular Frequency,Regular Value,45,1,2.222222
28,High Risk (61-90 days),Low Frequency,Low Value,763,14,1.834862
29,High Risk (61-90 days),Low Frequency,Regular Value,483,7,1.449275
30,High Risk (61-90 days),Low Frequency,Very High Value,150,2,1.333333
27,High Risk (61-90 days),Low Frequency,High Value,377,3,0.795756
8,Active (0-30 days),Regular Frequency,High Value,2819,0,0.000000
9,Active (0-30 days),Regular Frequency,Low Value,2077,0,0.000000
10,Active (0-30 days),Regular Frequency,Regular Value,3316,0,0.000000
5,Active (0-30 days),Low Frequency,Low Value,6392,0,0.000000
4,Active (0-30 days),Low Frequency,High Value,4069,0,0.000000
3,Active (0-30 days),High Frequency,Very High Value,3081,0,0.000000
2,Active (0-30 days),High Frequency,Regular Value,1331,0,0.000000

In [118]:
# ==========================================
# PLAN 3 - STEP 3.11
# Final Customer Segmentation
# ==========================================

def customer_segment(row):

    status = row["recency_band"]
    frequency = row["frequency_segment"]
    value = row["value_segment"]

    # 1. Champions
    if (
        status == "Active (0-30 days)"
        and frequency in ["High Frequency", "Very High Frequency"]
        and value in ["High Value", "Very High Value"]
    ):
        return "Champions"

    # 2. Valuable Active Customers
    elif (
        status == "Active (0-30 days)"
        and value in ["High Value", "Very High Value"]
    ):
        return "Valuable Active"

    # 3. High-Value At Risk
    elif (
        status == "At Risk (31-60 days)"
        and value in ["High Value", "Very High Value"]
    ):
        return "At-Risk Valuable"

    # 4. High-Value High Risk
    elif (
        status == "High Risk (61-90 days)"
        and value in ["High Value", "Very High Value"]
    ):
        return "High-Risk Valuable"

    # 5. High-Value Win-back
    elif (
        status == "Inactive (90+ days)"
        and value in ["High Value", "Very High Value"]
    ):
        return "High-Value Win-back"

    # 6. Standard Re-engagement
    elif status in [
        "At Risk (31-60 days)",
        "High Risk (61-90 days)",
        "Inactive (90+ days)"
    ]:
        return "Standard Re-engagement"

    # 7. Other Active Customers
    else:
        return "Regular Active"


customer_clean["customer_segment"] = (
    customer_clean.apply(
        customer_segment,
        axis=1
    )
)


# Segment summary
segment_summary = (
    customer_clean["customer_segment"]
    .value_counts()
    .reset_index()
)

segment_summary.columns = [
    "customer_segment",
    "customer_count"
]

segment_summary["percentage"] = (
    segment_summary["customer_count"]
    / total_customers
) * 100

segment_summary

         customer_segment  customer_count  percentage
0          Regular Active           18107   37.163147
1         Valuable Active           10882   22.334421
2               Champions           10389   21.322579
3  Standard Re-engagement            6255   12.837879
4        At-Risk Valuable            2294    4.708249
5      High-Risk Valuable             580    1.190403
6     High-Value Win-back             216    0.443322

In [119]:
# ==========================================
# PLAN 3 - STEP 3.12
# Final Customer-Level Validation
# ==========================================

print("Total rows:", len(customer_clean))
print(
    "Unique customers:",
    customer_clean["customer_id"].nunique()
)

print(
    "Duplicate customer IDs:",
    customer_clean["customer_id"].duplicated().sum()
)

print(
    "Missing churn labels:",
    customer_clean["churned"].isna().sum()
)

print(
    "Historical churned:",
    customer_clean["churned"].sum()
)

print(
    "Current status distribution:"
)

print(
    customer_clean["recency_band"]
    .value_counts()
)

print(
    "Customer segment total:",
    customer_clean["customer_segment"]
    .value_counts()
    .sum()
)

Total rows: 48723
Unique customers: 48723
Duplicate customer IDs: 0
Missing churn labels: 0
Historical churned: 780
Current status distribution:
recency_band
Active (0-30 days)        39378
At Risk (31-60 days)       6696
High Risk (61-90 days)     1896
Inactive (90+ days)         753
Name: count, dtype: int64
Customer segment total: 48723

In [120]:
# ==========================================
# PLAN 4 - STEP 4.1
# Final Customer Analysis Table
# ==========================================

customer_analysis = customer_clean[
    [
        "customer_id",
        "first_tx",
        "last_tx",
        "transaction_count",
        "customer_tenure_days",
        "avg_days_between_transactions",
        "recency_days",
        "recency_band",
        "frequency_segment",
        "total_spend",
        "avg_transaction_value",
        "value_segment",
        "retention_priority",
        "customer_segment",
        "churned"
    ]
].copy()


print("Rows:", len(customer_analysis))
print(
    "Unique Customers:",
    customer_analysis["customer_id"].nunique()
)

customer_analysis.head()

Rows: 48723
Unique Customers: 48723

,customer_id,first_tx,last_tx,transaction_count,customer_tenure_days,avg_days_between_transactions,recency_days,recency_band,frequency_segment,total_spend,avg_transaction_value,value_segment,retention_priority,customer_segment,churned
0,93716481,2023-01-05,2023-12-25,76,354,4.720000,4,Active (0-30 days),High Frequency,127670300,1.679872e+06,Very High Value,Healthy / Maintain,Champions,0
1,49020929,2023-02-05,2023-12-20,10,318,35.333333,9,Active (0-30 days),Low Frequency,54458100,5.445810e+06,High Value,Healthy / Maintain,Valuable Active,0
2,52690950,2023-01-31,2023-12-12,10,315,35.000000,17,Active (0-30 days),Low Frequency,6403350,6.403350e+05,Low Value,Healthy / Maintain,Regular Active,0
3,23199751,2023-01-10,2023-12-24,23,348,15.818182,5,Active (0-30 days),Regular Frequency,15184150,6.601804e+05,Low Value,Healthy / Maintain,Regular Active,0
4,61997066,2023-01-05,2023-11-27,18,326,19.176471,32,At Risk (31-60 days),Low Frequency,262340450,1.457447e+07,Very High Value,Re-engagement,At-Risk Valuable,0

In [121]:
# ==========================================
# PLAN 4 - STEP 4.2
# Final Customer Dataset Validation
# ==========================================

print("===== DATA TYPES =====")
print(customer_analysis.dtypes)

print("\n===== MISSING VALUES =====")
print(customer_analysis.isnull().sum())

print("\n===== DUPLICATE CUSTOMER IDs =====")
print(
    customer_analysis["customer_id"]
    .duplicated()
    .sum()
)

print("\n===== TOTAL ROWS =====")
print(len(customer_analysis))

print("\n===== UNIQUE CUSTOMERS =====")
print(
    customer_analysis["customer_id"]
    .nunique()
)

===== DATA TYPES =====
customer_id                               int64
first_tx                         datetime64[us]
last_tx                          datetime64[us]
transaction_count                         int64
customer_tenure_days                      int64
avg_days_between_transactions           float64
recency_days                              int64
recency_band                           category
frequency_segment                           str
total_spend                               int64
avg_transaction_value                   float64
value_segment                               str
retention_priority                          str
customer_segment                            str
churned                                   int64
dtype: object

===== MISSING VALUES =====
customer_id                      0
first_tx                         0
last_tx                          0
transaction_count                0
customer_tenure_days             0
avg_days_between_transactions    0
recency_days                     0
recency_band                     0
frequency_segment                0
total_spend                      0
avg_transaction_value            0
value_segment                    0
retention_priority               0
customer_segment                 0
churned                          0
dtype: int64

===== DUPLICATE CUSTOMER IDs =====
0

===== TOTAL ROWS =====
48723

===== UNIQUE CUSTOMERS =====
48723

In [122]:
# ==========================================
# PLAN 4 - STEP 4.3
# Transaction Dataset Structure
# ==========================================

print("Rows:", len(transaction_df))
print("Columns:")
print(transaction_df.columns.tolist())

print("\nData Types:")
print(transaction_df.dtypes)

print("\nMissing Values:")
print(transaction_df.isnull().sum())

Rows: 3159157
Columns:
['customer_id', 'date', 'amount', 'type']

Data Types:
customer_id             int64
date           datetime64[us]
amount                  int64
type                      str
dtype: object

Missing Values:
customer_id    0
date           0
amount         0
type           0
dtype: int64

In [123]:
# ==========================================
# PLAN 4 - STEP 4.4
# Prepare Final Transaction Table
# ==========================================

transaction_analysis = transaction_df[
    [
        "customer_id",
        "date",
        "amount",
        "type"
    ]
].copy()

print("Transaction rows:", len(transaction_analysis))
print("Transaction columns:", transaction_analysis.columns.tolist())
print("Missing values:")
print(transaction_analysis.isnull().sum())

Transaction rows: 3159157
Transaction columns: ['customer_id', 'date', 'amount', 'type']
Missing values:
customer_id    0
date           0
amount         0
type           0
dtype: int64

In [124]:
# ==========================================
# PLAN 4 - STEP 4.5
# Export Final Power BI Datasets
# ==========================================

import os

output_folder = r"D:\Customer_Churn_Retention_Analysis\02_Clean_Data"

os.makedirs(output_folder, exist_ok=True)


# Export customer-level dataset
customer_analysis.to_csv(
    os.path.join(
        output_folder,
        "customer_analysis.csv"
    ),
    index=False
)


# Export transaction-level dataset
transaction_analysis.to_csv(
    os.path.join(
        output_folder,
        "transaction_analysis.csv"
    ),
    index=False
)


print("Files exported successfully!")

print(
    "Customer file:",
    os.path.join(
        output_folder,
        "customer_analysis.csv"
    )
)

print(
    "Transaction file:",
    os.path.join(
        output_folder,
        "transaction_analysis.csv"
    )
)

Files exported successfully!
Customer file: D:\Customer_Churn_Retention_Analysis\02_Clean_Data\customer_analysis.csv
Transaction file: D:\Customer_Churn_Retention_Analysis\02_Clean_Data\transaction_analysis.csv